-- Il file è stato creato manualmente dal log creato da terminale
alter table if exists generations
drop constraint if exists FKs9nwd20pj13ghhy4jyfd6xdls

alter table if exists generations
drop constraint if exists FKbwliq1d6x50m0jjupv7mt46ym

alter table if exists location_datas
drop constraint if exists FKcj7ptxdw934r22b8caob3882m

alter table if exists points_of_interest
drop constraint if exists FKp34ij6gty88hydksyqrj4xooo

alter table if exists rents
drop constraint if exists FKtpgxnnpm5lsq48tt0r0d7mq7v

alter table if exists rents
drop constraint if exists FK7dewe65bc9vb6wh1c13ymnh5m

drop table if exists generations cascade

drop table if exists location_datas cascade

drop table if exists merchants cascade

drop table if exists points_of_interest cascade

drop table if exists rents cascade

drop table if exists sensors cascade

drop table if exists users cascade

create table generations (
                             point_of_interest_id integer,
                             id bigint not null,
                             location_data_id bigint not null unique,
                             advertisment varchar(255),
                             primary key (id)
)

create table location_datas (
                                latitude float4 not null,
                                longitude float4 not null,
                                fetch_time timestamp(6) not null,
                                id bigint generated by default as identity,
                                rent_id bigint not null,
                                primary key (id),
                                unique (fetch_time, rent_id)
)

create table merchants (
                           activity_name varchar(255) not null,
                           email varchar(255) not null,
                           vat varchar(255) not null,
                           primary key (vat)
)

create table points_of_interest (
                                    id integer generated by default as identity,
                                    latitude float4 not null,
                                    longitude float4 not null,
                                    merchant_vat varchar(255) not null,
                                    primary key (id),
                                    unique (latitude, longitude)
)

create table rents (
                       sensor_id integer not null,
                       end_time timestamp(6),
                       id bigint generated by default as identity,
                       start_time timestamp(6) not null,
                       user_email varchar(255) not null,
                       primary key (id),
                       unique (user_email, sensor_id, start_time)
)

create table sensors (
                         id integer generated by default as identity,
                         primary key (id)
)

create table users (
                       age integer not null,
                       gender smallint not null check (gender between 0 and 2),
                       email varchar(255) not null,
                       name varchar(255) not null,
                       surname varchar(255) not null,
                       primary key (email)
)

alter table if exists generations
    add constraint FKs9nwd20pj13ghhy4jyfd6xdls
    foreign key (location_data_id)
    references location_datas

alter table if exists generations
    add constraint FKbwliq1d6x50m0jjupv7mt46ym
    foreign key (point_of_interest_id)
    references points_of_interest

alter table if exists location_datas
    add constraint FKcj7ptxdw934r22b8caob3882m
    foreign key (rent_id)
    references rents

alter table if exists points_of_interest
    add constraint FKp34ij6gty88hydksyqrj4xooo
    foreign key (merchant_vat)
    references merchants

alter table if exists rents
    add constraint FKtpgxnnpm5lsq48tt0r0d7mq7v
    foreign key (sensor_id)
    references sensors

alter table if exists rents
    add constraint FK7dewe65bc9vb6wh1c13ymnh5m
    foreign key (user_email)
    references users