services:
  kafka:
    image: bitnami/kafka
    restart: always
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  postgis:
    image: postgis/postgis
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminadminadmin

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sweat.unipd@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Admin12!
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  # spring-backend:
  #   image: spring-backend
  #   restart: always
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgis:5432/admin
  #     - SPRING_DATASOURCE_USERNAME=admin
  #     - SPRING_DATASOURCE_PASSWORD=adminadminadmin
  #     - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #     - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
  #     - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
  #     - LANGCHAIN4J_OPEN-AI_CHAT-MODEL_API-key=demo
  #     - LANGCHAIN4J_OPEN-AI_CHAT-MODEL_MODEL-NAME=gpt-4o-mini
  #   depends_on:
  #     - kafka
  #     - postgis

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana

  # simulator:
  #   image: simulator
  #   environment:
  #     - BROKER=kafka:9092
  #   depends_on:
  #     - kafka

