networks:
  demo-net:
    driver: bridge

services:
  kafka:
    image: bitnami/kafka:latest
    networks:
      - demo-net
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  nifi:
    image: apache/nifi:latest
    networks:
      - demo-net
    ports:
      - 8443:8443
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=adminadminadmin
    volumes:
      - ./data/nifi/conf:/opt/nifi/nifi-current/conf
      - ./data/nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./data/nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./data/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./data/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./data/nifi/extensions:/opt/nifi/nifi-current/extensions
      - ./data/nifi/python_extensions:/opt/nifi/nifi-current/python_extensions
