spring.application.name=NearYou
spring.main.web-application-type=none
#DB config
spring.datasource.url=jdbc:postgresql://127.0.0.1/admin
spring.datasource.username=admin
spring.datasource.password=adminadminadmin
spring.jpa.hibernate.ddl-auto=none
#####spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
#Kafka config
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=io.github.sweatunipd.NearYou.infrastracture.adapters.input.dto
spring.kafka.consumer.properties.spring.json.value.default.type=io.github.sweatunipd.NearYou.infrastracture.adapters.input.dto.GPSDataDto
#OpenAI Config
#https://docs.langchain4j.dev/integrations/language-models/open-ai/#api-key
#https://docs.langchain4j.dev/tutorials/model-parameters
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini