name: Spring CI with Maven
on:
    push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.2
            - name: Set up JDK 23
              uses: actions/setup-java@v4.6.0
              with:
                  distribution: 'temurin'
                  java-version: 23
                  cache: 'maven'
            - name: Build with Maven (without tests atm)
              run: mvn clean package -DskipTests
            - name: Copy Jar
              run: mkdir deploy && cp target/NearYou-*.jar deploy
            - name: Deploy Jar in Github
              uses: actions/upload-artifact@v4.6.0
              with:
                  name: NearYou
                  path: deploy