name: Check linting of codebase
on:
    push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4.2.2
          - name: Check Java linting with Spotless
            run: mvn spotless:check
          - name: Check Typescript linting with Prettier
            run: |
              cd client
              npm ci
              npm run check-lint