name: Spring CI with Maven
on:
  push:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Start Docker services
        run: docker compose up -d
      - name: Set up JDK 23
        uses: actions/setup-java@v4.6.0
        with:
            distribution: 'temurin'
            java-version: 23
            cache: 'maven'
      - name: Test with Maven
        run: mvn test
      - name: Stop Docker services
        run: docker compose down
